# -*- coding: utf-8 -*-
"""0327_a107260103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kfOYQfu9Ow_Vq1catacFxbR960zLuLDg
"""

movie_title = "moana"
movie_rating = 7.6
movie_time = 107

print(movie_title)
print(movie_rating)
print(movie_time)

movie_time_hour = 1
movie_time_min = 47

movie_time_hour * 60 +movie_time_min

movie_time_hour + movie_time_min/60

8**0.5

8**1/3

8**(1/3)

55% 2

247% 15

current_tempc =29
current_tempf = current_tempc *9/5+32
print(current_tempf)

current_tempc = (current_tempf -32)/9*5
print(current_tempc)

oresama_h = 175
oresama_w = 65
oresama_bmi = oresama_w / (oresama_h/100)**2
print(oresama_bmi)

movie_title = 'moana'
print(movie_title )

movie_story_line="""In Ancient Polynesia, when a terrible curse incurred 
by the Demigod Maui reaches Moana's island,
she answers the Ocean's call to seek out the Demigod to set things right."""
print(movie_story_line)

WTF="what'the'fuck"
print(WTF)

wtf='what\'the\'fuck'
print(wtf)

MCD="i'm lovin' it!"
print(MCD)

BIGMAC='i \'m lovin\' it!'
print(BIGMAC)

#what did ross said?
shesaid = """Let's put aside the fact that you "accidentally" pick up my grandmother's ring"""
print(shesaid)

#文字嵌入 string interpolation
#{}挖洞 插入物件的值
"{}的評等是{}，片長為{}分鐘".format(movie_title,movie_rating,movie_time)

movie_title = "finding nemo"
movie_rating = 8.1
movie_time = 100
"{}的評等是{}，片長為{}分鐘".format(movie_title,movie_rating,movie_time)



movie_title = "finding nemo"
movie_rating = 8.1
movie_time = 100
number_of_ratings = 906432
# :.0f 四捨五入 :, 追加千分點 :.2f 追加兩位小數
"{}的評等是{:.0f}，基於{:,}個評分，片長為{:.2f}分鐘".format(movie_title,movie_rating,number_of_ratings,movie_time)

#imput
movie_title = input("請輸入電影名稱:")
movie_rating= input("請輸入電影評等:")



("{}的評等為{}").format(movie_title,movie_rating)

place = input("please enter your location:")
weather = input("please enter the weather:")

("我在{}，天氣{}").format(place,weather)

print(("我在{}，天氣{}").format(place,weather))

# 文字的 + & *
#設定為文字 " OR ' 之後使用+ 則使文字疊加
print("我好"+"帥")

print("我在"+place+"天氣"+weather)

#布林
print(True)
print(False)

print(type(True))
print(type(False))

print(87==63)
print(8763!=8763)

print(movie_rating >= 6)

id_last = 8
print(id_last%2== 1)
#判斷是否為奇數
#ANS 語法使用/2餘數是否為1