# -*- coding: utf-8 -*-
"""0410_a107260103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tjywV95zZ_9bol5uQFOM2WVJ_azvZKsN
"""

print(False)
print(True)

print(type(7.7 > 8))
print(type(7.7!= 8))

print(7.7==8)

print(7!=8)

print(5566.00==5566)
print(type(5566.00))
print(type(5566))

print(157 is 120
    )

print(157<200 and 157>158)

print(1>2 or 1<2)

id_last_digit = input("please type")
id_last_digit = int(id_last_digit)
print(id_last_digit)
print (type(id_last_digit))
modulo = id_last_digit % 2
ans = modulo == 1
print(ans)

print(float('5566'))
print(int('5566'))

print(int(False))
print(float(True))