# -*- coding: utf-8 -*-
"""0522_a107260103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNEDTECEUaWx4mscn7VAYJFeii1_qISW
"""

# iterables in python
prime_list = [2, 3, 5, 7, 11]
prime_tuple = (2, 3, 5, 7, 11)
weekdays_dict = {
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5
}
prime_set = {2, 3, 5, 7, 11}

I = iter(prime_list)
next(I)

I = iter(prime_tuple)
next(I)

I = iter(weekdays_dict)
next(I)

I = iter(weekdays_dict.keys())
next(I)

I = iter(weekdays_dict.values())
next(I)

I = iter(weekdays_dict.items())
next(I)

I = iter(prime_set)
next(I)

may4th = "Luke, use the Force!"
I = iter(may4th)
next(I)

iter(5566)

for i in may4th:
    print(i)

may4th[0]
may4th[len(may4th)-1]

print(list(range(1, 101)))

print(list(range(0, 100, 2)))

for i in range(1, 101):
    print(i)

x = int(input("請輸入起始的正整數:"))
y = int(input("請輸入終止的正整數:"))
odds = []
for i in range(x, y+1):
    mod = i % 2
    if mod == 1:
        odds.append(i)
print(odds)

print(len(odds)) # 記數
print(sum(odds)) # 加總

x = int(input("請輸入一個正整數:"))
divisors = []
for i in range(1, x+1):
    if x % i == 0:
        divisors.append(i)
print(divisors)
n_divisors = len(divisors)
if n_divisors == 2:
    print("{}是質數".format(x))
else:
    print("{}不是質數".format(x))

x = int(input("請輸入一個正整數:"))
divisors = []
for i in range(1, x+1):
    if x % i == 0:
        divisors.append(i)
print(divisors)

# random 產生 1 個隨機數
import random

random.randint(1, 1000)
# random 產生 100 個隨機數
random_integers = []
for i in range(100):
    rand_int = random.randint(1, 1000)
    random_integers.append(rand_int)
print(random_integers)
print(len(random_integers))
# 找出第一大與第一小的數字
print(max(random_integers))
print(min(random_integers))
# 找出第二大與第二小的數字
rand_int_unique = set(random_integers)
rand_int_unique_list = list(rand_int_unique)
print(rand_int_unique_list)
rand_int_unique_list.sort()
print(rand_int_unique_list[1])  # second min
print(rand_int_unique_list[-2]) # secomd max

list(range(10))

squared = []
for i in range(10):
    squared.append(i**2)
print(squared)

squared = [i**2 for i in range(10)]
print(squared)

odds_squared = []
for i in range(10):
    if i % 2 == 1:
        odds_squared.append(i**2)
print(odds_squared)

odds_squared = [i**2 for i in range(10) if i % 2 == 1]
print(odds_squared)

random_integers = [random.randint(1, 100) for i in range(20)]
is_odd_ints = []
for i in random_integers:
    if i % 2 == 1:
        is_odd_ints.append(True)
    else:
        is_odd_ints.append(False)
print(random_integers)
print(is_odd_ints)

random_integers = [random.randint(1, 100) for i in range(20)]
is_odd_ints = [True if i % 2 == 1 else False for i in random_integers]
print(random_integers)
print(is_odd_ints)

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
for i, wd in enumerate(weekdays):
    print("{}:星期{}".format(wd, i+1))

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for idx, movie in enumerate(avengers):
    print("第 {} 部上映的復仇者聯盟電影:{}".format(idx+1, movie))

years = [2012, 2015, 2018, 2019]
for year, movie in zip(years, avengers):
    print("{}上映的年份是{}".format(movie, year))

