# -*- coding: utf-8 -*-
"""A107260103_0501

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GoGw-R86vyqC0ZD0zU-DX2U_4QhDMnXU
"""

x=int(input("typeinanumber"))
i = 1 #start
while i <= x: #stop
 print(i)
 i+= 1#step

x = int (input("輸入一個正整數"))
i = 1 # start
divisor_counter = 0 # 歸0
while i <= x: #stop
 if x % i == 0:
    divisor_counter += 1
    print("{}可以被{}整除".format(x.i))
    print("因次目前因數有{}個".format(divisor_counter))
    print("=====")
 i+= 1 #step
print("ans")
print("{}有{}個因數".format(divisor_counter))
if divisor_counter ==2:
  print("{}是植樹".format(X))
else:
  print("{}不是植樹",format(x))

i = 1
while i <= 100: #stop
 if i % 15==0:
  print("fizz buzz")
 elif i % 3 ==0:
  print("fizz")
 else i % 5 ==0:
  print("buzz")
  i += 1 #step