# -*- coding: utf-8 -*-
"""a107260103_0417.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AT8T6BjowibfzAbkfK6YKCZ6zAfzE-HZ
"""

member_ages = [15, 20, 25, 30, 35, 46]
list(filter(lambda:))

#資料篩選(begin)

if True:
  print("真")

if False:
  print("真")
  #偵測IF後的保留字為True則會執行第二行(縮排) False則會跳過
print("假")

movie_title =input('電影名稱')
movie_rating =input('電影評分')
movie_rating= float(movie_rating)

if movie_rating>7:
  print("{}評分為{}分 讚喔".format(movie_title, movie_rating))

salary = input("月薪:")
saving = input("存款:")
#做型別轉換
#使用INT?
salary = float(salary)
saving = float(saving)
if salary>30000:
  print("發卡囉")
if salary<=30000:
  print("GG")
if saving>300000:
  print("發卡囉")
if saving<=300000:
  print("GG")

salary = input("月薪:")
saving = input("存款:")
#做型別轉換
#使用INT?
salary = int(salary)
saving = int(saving)
print(type(salary))
print(type(saving))
#單向判斷 未達成則無聲卡 ANS""中不放物件(空字串)
ans = ""
#條件判斷
if salary>30000:
  ans = "發卡囉"
if saving>300000:
  ans = "發卡囉"
#判斷over
print(ans)
#未設定則一超過即達成

salary = input("月薪:")
saving = input("存款:")
salary = int(salary)
saving = int(saving)
print(salary > 30000 and saving > 300000)
#and(交集)需要兩個都符合
#or(聯集)則只要一個即可
#可簡化判斷式
#if else

#判斷奇偶數
user_int = input("type in a number")
user_int = int(user_int)
if user_int % 2 ==0:
  ans = "even"
else:
  ans = "odd"
print(ans)

idcard = input("type in the last number")
idcard = int (idcard)
if idcard % 2 == 0:
  ans = "you can buy on tuseday"
else:
  ans = "you can buy on monday"
print(ans)

help(id)

idcard = input("type")
id_last_digit = idcard[-1]
id_last_digit = int(id_last_digit)
if id_last_digit %2==0:
  ans = "246"
else:
  ans= "135"
print(ans)

#bMi
height=input("height")
weight=input("weight")
height=float(height)
weight=float(weight)

BMI = weight/(height*0.01)**2
if BMI >30:
  label="obese"
elif BMI > 25:
  label="overweight"
elif BMI>18.5:
  label="normalnormal"
else:
  label="underweight"
print(label)